config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'comment/create'
  root to: 'plant_species#index'
  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources 'plant_species' do
    collection do
      get 'search'
    end
  end

  resources 'collected_plants', only: %i[new create index destroy update] do
    collection do
      get 'watering_report'
    end
  end
  
  resources 'comments', only: :create
end

app/models/collected_plant.rb
# == Schema Information
#
# Table name: collected_plants
#
#  id                :integer          not null, primary key
#  last_time_watered :datetime
#  nick_name         :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  owner_id          :integer          not null
#  species_id        :integer          not null
#
# Indexes
#
#  index_collected_plants_on_last_time_watered  (last_time_watered)
#  index_collected_plants_on_nick_name          (nick_name)
#  index_collected_plants_on_owner_id           (owner_id)
#  index_collected_plants_on_species_id         (species_id)
#
# Foreign Keys
#
#  owner_id    (owner_id => users.id)
#  species_id  (species_id => plant_species.id)
#
class CollectedPlant < ApplicationRecord
  validate :last_time_watered_is_date
  belongs_to :species, class_name: 'PlantSpecies', inverse_of: :collected_plants
  belongs_to :owner, class_name: 'User', inverse_of: :collected_plants

  def name
    "#{nick_name.presence || '[UNNAMED]'} - #{species.name}"
  end

  def next_time_to_water
    return if last_time_watered.nil?

    last_time_watered + species.watering_interval.days
  end

  def hours_underwatered
    diff = (Time.current - next_time_to_water)
    (diff / 1.hour).round
  end

  def needs_water?
    return false if last_time_watered.nil?
    return true if last_time_watered > next_time_to_water

    false
  end

  def watering_status
    return :unknown if last_time_watered.nil?
    return :content if hours_underwatered.negative?
    return :wanting if hours_underwatered.between?(0, 48)

    :deprived
  end

  private

  def last_time_watered_is_date
    return if last_time_watered.nil?

    unless last_time_watered.is_a?(Time)
      errors.add(:last_time_watered, 'must be a valid date')
    end
  end
end

app/controllers/collected_plants_controller.rb
class CollectedPlantsController < ApplicationController
  before_action :authenticate_user!, :set_active_header

  def create
    plant = CollectedPlant.new(collected_plant_params)
    plant.owner = current_user
    if plant.save
      flash[:notice] = 'New plant added to collection'
      redirect_to collected_plants_url
    else
      flash[:alerts] = ['Failed to add new plant to collection']
      plant.errors.full_messages.each { |error| flash[:alerts].push(error) }
      redirect_to plant_species_index_url
    end
  end

  def index
    @collected_plants = current_user.collected_plants.includes(:species)
    @opened = params[:opened].to_i
  end

  def destroy
    plant = current_user.collected_plants.find(params[:id])

    if plant.destroy
      flash[:notice] = 'Successfully removed plant from collection'
    else
      flash[:alerts] = ['Failed to remove plant from collection']
      plant.errors.full_messages.each { |error| flash[:alerts].push(error) }
    end

    redirect_to collected_plants_url
  end

  def update
    plant = current_user.collected_plants.find(params[:id])

    if plant.update(last_time_watered: Time.current)
      flash[:notice] = "Successfully watered #{plant.nick_name || 'plant'}"
    else
      flash[:alerts] = ['Failed to water plant from collection']
      plant.errors.full_messages.each { |error| flash[:alerts].push(error) }
    end

    redirect_to collected_plants_url
  end

  def watering_report
    @plants = current_user.collected_plants.order(last_time_watered: :desc)
  end

  private

  def collected_plant_params
    params.require(:collected_plant).permit(:species_id, :nick_name)
  end

  def set_active_header
    @active_header ||= :collected_plants
  end
end

app/helpers/collected_plants_helper.rb
module CollectedPlantsHelper
    def water_status_color(plant)
        case plant.watering_status
        when :deprived
            'danger'
        when :wanting
            'warning'
        when :content
            'success'
        else
            'default'
        end
    end

    def last_watered_date_in_words(plant)
        return '[UNKNOWN]' if plant.last_time_watered.nil?

        "#{time_ago_in_words(plant.last_time_watered).titleize} Ago"
    end

    def formatted_water_time(datetime)
        return if datetime.nil?

        datetime.strftime('%a, %D')
    end
end

app/views/collected_plants/_new_modal.html.erb
<div class="modal fade" id="<%= id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Plant to My Collection</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%= form_with(model: collected_plant) do |form| %>
                    <%= form.hidden_field :species_id, value: species.id %>

                    <div class="mb-3">
                        <%= form.label :nick_name, "Nick Name", class: "form-label" %>
                        <%= form.text_field :nick_name, class: "form-control" %>
                    </div>

                    <%= form.submit "Add", class: "btn btn-success" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/collected_plants/_no_collected_alert.html.erb
<div class="row">
    <div class="col alert alert-primary alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">You don't have any plants in your collection yet</h4>

        <p>Add some new plants to your collection, and then you can manage them here</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>

app/views/collected_plants/destroy.html.erb
<h1>CollectedPlants#destroy</h1>
<p>Find me in app/views/collected_plants/destroy.html.erb</p>

app/views/collected_plants/index.html.erb
<div class="container">
    <h1>My Plant Collection</h1>

    <% if @collected_plants.empty? %>
        <%= render partial: 'collected_plants/no_collected_alert' %>
    <% end %>

    <%= link_to "Generate Watering Report", watering_report_collected_plants_url, class: 'btn btn-primary gy-2' %>

    <div class="accordion" id="plantCollectionAccordion">
        <% @collected_plants.each do |plant| %>
            <% labelId = "accordionHeader-#{plant.id}" %>
            <% collapseId = "collapsePlant-#{plant.id}" %>
            <% opened =  @opened == plant.id %>
            <div class="accordion-item">
                <h2 class="accordion-header" id="<%= labelId %>">
                    <button class="accordion-button <%= "collapsed" unless opened %>" type="button" data-bs-toggle="collapse" data-bs-target="#<%= collapseId %>" aria-expanded="<%= opened %>" aria-controls="<%= collapseId %>">
                        <%= plant.name %>
                    </button>
                </h2>

                <div id="<%= collapseId %>" class="accordion-collapse collapse <%= "show" if opened %>" aria-labelledby="<%= labelId %>" data-bs-parent="#plantCollectionAccordion">
                    <div class="accordion-body row">
                        <div class="col-md">
                            <h4>Last Watered</h4> 
                            <p class="text-<%= water_status_color(plant) %>"><%= last_watered_date_in_words(plant) %></p>

                            <h4>Added to Collection</h4>
                            <p><%= plant.created_at %></p>

                            <h4>Actions</h4>
                            <div class="btn-group">
                                <%= button_to "Water Now", collected_plant_url(plant), method: :put, class: 'btn btn-primary' %>
                                <%= button_to 'Remove', collected_plant_url(plant), method: :delete, class: "btn btn-danger" %>
                            </div>
                        </div>

                        <div class="col-md">
                            <h4>Species Info</h4>
                            <%= render partial: 'plant_species/card', locals: { plant_species: plant.species, details: true } %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/collected_plants/update.html.erb
<h1>CollectedPlants#update</h1>
<p>Find me in app/views/collected_plants/update.html.erb</p>

app/views/collected_plants/watering_report.html.erb
<div class="container">
    <h1>Watering Report</h1>

    <% if @plants.empty? %>
        <%= render partial: 'collected_plants/no_collected_alert' %>
    <% end %>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nick Name</th>
                <th scope="col">Species</th>
                <th scope="col">Watering Status</th>
                <th scope="col">Last Time Watered</th>
                <th scope="col">Next Watering</th>
            </tr>
        </thead>

        <tbody>
            <% @plants.each.with_index do |plant, idx| %>
                <tr class="table-<%= water_status_color(plant) %>">
                    <th scope="row"><%= idx + 1 %></th>
                    <td><%= link_to plant.nick_name, collected_plants_url(opened: plant.id) %></td>
                    <td><%= plant.species.name %></td>
                    <td><%= plant.watering_status %></td>
                    <td><%= formatted_water_time(plant.last_time_watered) %></td>
                    <td><%= formatted_water_time(plant.next_time_to_water) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>