config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'comment/create'
  root to: 'plant_species#index'
  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources 'plant_species' do
    collection do
      get 'search'
    end
  end

  resources 'collected_plants', only: %i[new create index destroy update] do
    collection do
      get 'watering_report'
    end
  end
  
  resources 'comments', only: :create
end

app/controllers/plant_species_controller.rb
class PlantSpeciesController < ApplicationController
  before_action :authenticate_user!, :set_active_header

  def index
    @plant_species = PlantSpecies.all
    @collected_plant = CollectedPlant.new
  end

  def new
    @plant_species = PlantSpecies.new
  end

  def create
    @plant_species = PlantSpecies.new(plant_species_params)

    if @plant_species.save
      flash[:notice] = 'Saved new plant species'
      redirect_to plant_species_url(@plant_species.id)
    else
      flash[:alerts] = ['Failed to save new plant species']
      @plant_species.errors.full_messages.each { |error| flash[:alerts].push(error) }
      render :new
    end
  end

  def show
    @plant_species = PlantSpecies.includes(comments: :author).find(params[:id])
  end

  def edit
    @plant_species = PlantSpecies.find(params[:id])
  end

  def update
    @plant_species = PlantSpecies.find(params[:id])

    if @plant_species.update(plant_species_params)
      flash[:notice] = "Plant Species #{@plant_species.scientific_name} updated!"
      redirect_to plant_species_url(@plant_species)
    else
      flash[:alerts] = ['Failed to update plant species']
      @plant_species.errors.full_messages.each { |error| flash[:alerts].push(error) }
      render :edit
    end
  end

  def destroy
    @plant_species = PlantSpecies.find(params[:id])

    if @plant_species.destroy
      flash[:notice] = "Deleted #{@plant_species.scientific_name}"
    else
      flash[:alerts] = ["Failed to delete #{@plant_species.scientific_name}"]
      @plant_species.errors.full_messages.each { |error| flash[:alerts].push(error) }
    end

    redirect_to plant_species_index_url
  end

  def search
    @found_plant_species = PlantSpecies.with_scientific_name_like(query).or(PlantSpecies.with_common_name_like(query))
    @collected_plant = CollectedPlant.new
  end

  private

  def query
    @query ||= params[:query]
  end

  def plant_species_params
    params.require(:plant_species).permit(:scientific_name, :common_name, :care_instructions, :light_level, :watering_interval)
  end

  def set_active_header
    @active_header ||= :plant_species
  end
end

app/helpers/plant_species_helper.rb
module PlantSpeciesHelper
    def light_level_select_options
        PlantSpecies.light_levels.map { |light_level, _| [light_level.titleize, light_level] }
    end
end

app/views/plant_species/_card.html.erb
<div class="card" style="width: 20rem;">
    <div class="card-body">
        <h5 class="card-title"><%= plant_species.scientific_name %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= plant_species.common_name %></h6>
        <% if local_assigns[:details] && details %>
            <hr>
            <h6>Care Instructions</h6>
            <p class="card-text"><%= plant_species.care_instructions %></p>
            <hr>
            <h6>Light Level</h6>
            <p class="card-text"><%= plant_species.light_level.titleize %></p>
            <h6>Watering Interval</h6>
            <p class="card-text">Once every <strong><%= plant_species.watering_interval %> day(s)</strong></p>
        <% end %>

        <div class="d-flex justify-content-between">
            <% if local_assigns[:btns] && btns.include?(:show) %>
                <%= link_to "Show", plant_species_url(plant_species),
                    class: "card-link btn btn-primary" %>
            <% end %>
            <% if local_assigns[:btns] && btns.include?(:edit) %>
                <%= link_to "Edit", edit_plant_species_url(plant_species),
                class: "card-link btn btn-secondary" %>
            <% end %>
            <% if local_assigns[:btns] && btns.include?(:add) %>
                <% modal_id = "addCollectionBtn-#{plant_species.id}" %>
                <%= button_tag "Add", type: "button", class: "btn btn-success", data: { 'bs-toggle' => 'modal', 'bs-target' => "\##{modal_id}" }  %>
                <%= render partial: 'collected_plants/new_modal', locals: { species: plant_species, id: modal_id, collected_plant: collected_plant } %>
            <% end %>
            <% if local_assigns[:btns] && btns.include?(:delete) %>
                <%= form_with url: plant_species_url(plant_species), method: :delete do |form| %>
                    <%= form.submit "Delete", class: "btn btn-danger" %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/plant_species/_form.html.erb
<%= form_with(model: plant_species) do |form| %>
    <div class="mb-3">
        <%= form.label :scientific_name, "Scientific Name", class: "form-label" %>
        <%= form.text_field :scientific_name, class: "form-control" %>
    </div>

    <div class="mb-3">
        <%= form.label :common_name, "Common Name", class: "form-label" %>
        <%= form.text_field :common_name, class: "form-control" %>
    </div>

    <div class="mb-3">
        <%= form.label :care_instructions, "Care Instructions", class: "form-label" %>
        <%= form.text_area :care_instructions, class: "form-control" %>
    </div>

    <div class="mb-3">
        <%= form.label :light_level, "Light Level", class: "form-label" %>
        <%= form.select :light_level, light_level_select_options, { selected: plant_species.light_level },
                        class: "form-select", 'aria-label' => ".form-select-md" %>
    </div>

    <div class="mb-3">
        <%= form.label :watering_interval, "Watering Interval (Days)", class: "form-label" %>
        <%= form.number_field :watering_interval, class: "form-control" %>
    </div>

    <%= form.submit btn_name, class: "btn btn-success" %>
<% end %>

app/views/plant_species/create.html.erb
<h1>PlantSpecies#create</h1>
<p>Find me in app/views/plant_species/create.html.erb</p>

app/views/plant_species/destroy.html.erb
<h1>PlantSpecies#destroy</h1>
<p>Find me in app/views/plant_species/destroy.html.erb</p>

app/views/plant_species/edit.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-3">
            <h1>Update "<%= @plant_species.scientific_name %>"</h1>
            <%= render partial: 'plant_species/form', locals: { btn_name: "Update", plant_species: @plant_species } %>
        </div>
    </div>
</div>

app/views/plant_species/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Plant Species</h1>
        </div>
    </div>

    <div class="row gy-2">
        <div class="col">
            <%= link_to "Add New", new_plant_species_url, class: "btn btn-success" %>
        </div>
    </div>

    <div class="row gy-2">
        <% @plant_species.each do |plant_species| %>
            <div class="col col-md-4 me-auto">
                <%= render  partial: 'plant_species/card',
                            locals: { plant_species: plant_species, btns: [:show, :add], collected_plant: @collected_plant } %>
            </div>
        <% end %>
    </div>
</div>

app/views/plant_species/new.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-3">
            <h1>New Plant Species</h1>
            <%= render partial: 'plant_species/form', locals: { btn_name: "Save", plant_species: @plant_species } %>
        </div>
    </div>
</div>

app/views/plant_species/search.html.erb
<div class="container">
    <div class="row">
        <h1>Search Results:</h1>

        <p>Found <%= @found_plant_species.count %> results</p>
    </div>

    <div class="row">
        <% @found_plant_species.each do |plant_species| %>
            <%= render  partial: 'plant_species/card',
                        locals: { plant_species: plant_species, btns: [:show, :add], collected_plant: @collected_plant } %>
        <% end %>
    </div>
</div>

app/views/plant_species/show.html.erb
<div class="container">
    <h1>"<%= @plant_species.scientific_name %>" Information</h1>
    <div class="row">
        <div class="col-md-auto">
            <%= render  partial: 'plant_species/card',
                        locals: { plant_species: @plant_species, btns: [:edit, :delete], details: true} %>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col">
            <h2>New Comment</h2>

            <%= form_with(model: Comment.new) do |form| %>
                <%= form.hidden_field :commentable_id, value: @plant_species.id %>
                <%= form.hidden_field :commentable_type, value: 'PlantSpecies' %>

                <div class="mb-3">
                    <%= form.text_area :body, class: "form-control" %>
                </div>

                <%= form.submit 'Comment', class: 'btn btn-success' %>
            <% end %>
        </div>
    </div>

    <hr>

    <div class="row">
        <h2>Comments</h2>

        <% if @plant_species.comments.empty? %>
            <p>No comments yet</p>
        <% else%>
            <ul class="list-group" style="list-style: none">
                <% @plant_species.comments.each do |comment| %>
                    <%= render partial: 'comments/list_item', locals: { comment: comment } %>
                <% end %>
            </ul>
        <% end %>
    </div>
</div>

app/views/plant_species/update.html.erb
<h1>PlantSpecies#update</h1>
<p>Find me in app/views/plant_species/update.html.erb</p>