config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'comment/create'
  root to: 'plant_species#index'
  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources 'plant_species' do
    collection do
      get 'search'
    end
  end

  resources 'collected_plants', only: %i[new create index destroy update] do
    collection do
      get 'watering_report'
    end
  end
  
  resources 'comments', only: :create
end

app/views/layouts/_alerts.html.erb
<div class="container">
    <div class="row">
        <div class="col alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">Alert!</h4>

            <%= alerts.map { |alert| "<p>#{alert}</p>" }.join("<hr>").html_safe %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/_header.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Plantera</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Plant Species", plant_species_index_url, class: "nav-link #{"active" if active == :plant_species}" %>
        </li>

        <li class="nav-item">
          <%= link_to "My Collection", collected_plants_url, class: "nav-link #{"active" if active == :collected_plants}" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            My Account
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><h5 class="dropdown-header">Username:</h5></li>
            <li><h5 class="dropdown-header"><%= current_user.username %></h5></li>
            <li><h5 class="dropdown-header">Email:</h5></li>
            <li><h5 class="dropdown-header"><%= current_user.email %></h5></li>
            <li><hr class="dropdown-divider"></li>
            <li>
            <%= form_with(url: destroy_user_session_path , method: :delete) do |f| %>
              <%= f.submit "Logout", class: 'dropdown-item btn btn-outline-danger' %>
            <% end %>
            </li>
          </ul>
        </li>
      </ul>
      <%= form_with url: search_plant_species_index_url, method: :get, class: "d-flex" do |form| %>
        <%= form.text_field :query, value: @query, type: "search", placeholder: "Search Plants", class: "form-control me-2", 'aria-label' => "Search" %>
        <%= form.submit "Search", class: "btn btn-outline-success" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<div class="container">
    <div class="row">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <p><%= notice %></p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Plantera</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render partial: 'layouts/header', locals: { active: @active_header } unless @disable_header %>
    <%= render partial: 'layouts/notice', locals: { notice: flash[:notice] }  if flash[:notice] %>
    <%= render partial: 'layouts/alerts', locals: { alerts: flash[:alerts] }  if flash[:alerts] %>

    <%= yield %>
</body>

</html>